sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: ZnhRLQlJ9X8ui9YdYus3eIbErjHehNHESV4TyCtGtVXOQjJ/j3hrh+h0AK3EsdM7Icy3n048YmMgRnwei1sbMJ0P1F9JvRpVeojcbsujU/ETrSDgEM0PgA82447Gy74554VCCJseDFv8VZs8nTOD66zImG7J0nN1R5iG8WWOi6fiqbRJPMzd6aZ6fBYRLK1OZ29Ym05ySGjeCzmBF3DRlaBI/CySpqkPC1zqmwlHW6a5M5vTlRrzzlz+t/osqMVhLUhDQW+PC2gXA/McCRH6AlMSAN/Iq/OwasA1TUiBG3gZENa0ooqddBHgcQPS+4T+FPXloqyNf9AsBKPvnlIVLY/DGmfSrFm/tf747fR8Kaz4JdSmTSAl3nQU3a8Vr4/Iqt4rMkcrBlB1LlQNbbXnEwLVQKLhXDKYxw2F+AWleNXapg4OLuBIISSZc0VR6YEIwcrcG3WWQ7WZKRjMEoZQJZUxFKDNuTPjD+B7OFMbjbfKKDaLMb2WyJM+wdz2GcGHM+rRddnQD3oR4g6UlGnkaxx9NoeO49tDDmnxs5gyKwnMAKWzP0vBoAfxXRT7EZ91a97ql0oW6UWp6/zG54CFNbjpO52A/iz/Ef7gksIm/FMP35doGLtXLeuSMPtHYYA6BJkAyQ2Eiqktn6uGp57XCgJ8fsiAna/HD1tQ/uRtF8U=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: bGW6sPVFQYsm76swLxugpla8WL+cbXiWmGM5ekWfic0Gt0ZVH0TRP3+5oovLTmIAY3GWP5M3cxTS8S+0YPZly0qApamUS1YqUVDhmtmIgaeauLB0Iu9J3eqS3F0hZcXz5oAKOTfjMKAUcQDuIwgtPVcZRN+GW0SgBfouNNnhZrNs7+ErkzM/a0VGpjEmSUGP7tSLIJmJWddjUraZQlWhyiyChtO1DfX7rHA9i9QwjCqDza+XLudVvkSCknIkElNpWBjh8deZR6wNyCUDg0A5bQWd5FITExTv8CMzewZYdcYbAp9MsHuAl6CQyIc2UVd01We3u0zhlVDDrklyX6W/JLc+B4pPxf9bLb8sQKloa2VmAfUenSF/yFnHPeEu/YFiD1JJdL2RjHzRiz0OahK8QJvp1QdAnAuRwYhG7cJQifCO3EVhk37Wreil3QY+FJGnQDsOyiC21QYX/aXrJf1dSgP04qRR7wok236bmz3nTJhOVc22HA6hQboRo4eSNzHMnW03m3Ct5PyMlu+lCyej9/RSf77INfs9GjCLAXuKWVAunI060TqHbr1eJg3a23gyRfrTrIVAv+qaTsFSFA476ozaIQh2grBViat01zH2w7d5jJkwVzXKvDMvVsssdTzhZZxNhg+HW3TKtBCD/HvSx5Vqki78B1Jt63qyOtbJzEE=
